- traveller/modules/schedule/forms.py
- traveller/static/themes/front/conftheme/2021/parts/schedule.html
> only allow to schedule one talk at a time

- .github/workflows/tests.yaml
uncommenting the `testing.yaml` code that was commented in #26 for experimenting.
> CI: run tests on desired OS and python version

- traveller/static/themes/front/conftheme/2021/parts/base.html
- traveller/static/themes/front/conftheme/2021/parts/talk_actions.html
Added a back button for returning to the user profile from the submitted talk settings.
Also, added a CSS style to remove background-image from anchor tags.
This fixes #9.
> BugFix: Add back button to edit talk view. This fixes issue #9

- traveller/modules/y/view.py
> BugFix: Prevent error when no reviewers present

- README.md
- traveller/modules/schedule/view.py
Readme updated with a dropdown with setup instructions for MySQL for first time users
> Added setup instructions for first time MySQL users

- traveller/modules/box__default/dashboard/tests/test_dashboard.py
- traveller/modules/box__default/dashboard/view.py
> fix : #33 Remove Notif test popup when a user successfully logs in

- traveller/modules/conf/models.py
- traveller/modules/conf/view.py
Problem: Prevent the user from adding days from a different year
A way to handle this issue: #37
Conf.add_days will validate and add the dates
The function will also check if the start date is before endate
Will throw a Value error if the conditions are not met
> added a method to validate and add conf dates 

- traveller/modules/y/view.py
- traveller/static/themes/front/conftheme/2021/parts/about_us.html
- traveller/static/themes/front/conftheme/2021/parts/base.html
- traveller/static/themes/front/conftheme/2021/parts/blog.html
- traveller/static/themes/front/conftheme/2021/parts/contact_us.html
- traveller/static/themes/front/conftheme/2021/parts/livestream.html
- traveller/static/themes/front/conftheme/2021/parts/privacy_policy.html
> Feat: Added the about us page, contact us page, data privacy policy page, livestream setup page, and blog page

- .gitignore
- traveller/modules/cfp/forms.py
- traveller/modules/cfp/view.py
- traveller/modules/conf/models.py
- traveller/modules/schedule/forms.py
- traveller/modules/schedule/models.py
- traveller/modules/schedule/view.py
- traveller/static/themes/front/conftheme/2021/parts/schedule.html
> BugFix: Show only accepted talks from the current year when building schedule. 

- traveller/modules/profile/view.py
> BugFix: Wrong page return after edit name in profile. 

- traveller/modules/cfp/forms.py
- traveller/modules/cfp/view.py
- traveller/modules/conf/models.py
- traveller/modules/schedule/forms.py
- traveller/modules/y/view.py
- traveller/static/themes/front/conftheme/2021/parts/cfp.html
- traveller/static/themes/front/conftheme/2021/parts/final_talk_action.html
- traveller/static/themes/front/conftheme/2021/parts/talk_actions.html
> Feature: Add textarea for adding co-authors to talks by email address. 

- traveller/modules/cfp/view.py
- traveller/modules/conf/models.py
- traveller/static/themes/front/conftheme/2021/parts/profile.html
> Feature: Implement delete talk from user. 

- traveller/modules/conf/models.py
- traveller/static/themes/front/conftheme/2021/parts/final_talk_action.html
- traveller/static/themes/front/conftheme/2021/parts/talk_actions.html
> Feature: Add the option for admin to delete talks in leaderboard. 

- traveller/modules/cfp/forms.py
> Bug: People should not be able to choose year when submitting talk.

- traveller/helpers/c2021/notif.py
- traveller/modules/cfp/view.py
- traveller/modules/conf/models.py
- traveller/static/themes/front/conftheme/2021/parts/cfp.html
> BugFix: Raise validation error if user submits talk without filling the required fields

- traveller/static/themes/front/conftheme/2021/index.html
- traveller/static/themes/front/conftheme/2021/parts/base.html
- traveller/static/themes/front/conftheme/2021/parts/setup.html
https://github.com/FlaskCon/traveller/issues/132
> Issue132: Proof read website copy

- traveller/modules/cfp/view.py
- traveller/modules/schedule/view.py
> BugFix: Error popup cannot be dismissed. 

- traveller/modules/schedule/forms.py
- traveller/modules/schedule/models.py
- traveller/modules/schedule/view.py
- traveller/static/themes/front/conftheme/2021/index.html
- traveller/static/themes/front/conftheme/2021/parts/base.html
- traveller/static/themes/front/conftheme/2021/parts/schedule.html
> Feature: add delete and edit button for days. 

- traveller/seed.py
to resolve the immediate concern in:
setup not working #142 
I added a year to the seed data object, because there was a change to the model that demanded non null values.
> #142 update seed command for recent model change

- traveller/static/themes/front/conftheme/2021/index.html
- traveller/static/themes/front/conftheme/2021/parts/base.html
Fixes [#140](https://github.com/FlaskCon/traveller/issues/140)
Thanks for the open source contributing experience guys.
> Fixed some website warnings

- traveller/modules/cfp/view.py
- traveller/modules/schedule/view.py
- traveller/static/themes/front/conftheme/2021/parts/final_talk_action.html
- traveller/static/themes/front/conftheme/2021/parts/schedule.html
- traveller/static/themes/front/conftheme/2021/parts/talk_actions.html
> BugFix: When deleting talk in leaderboard (as admin) redirects to profile page.

- traveller/modules/cfp/view.py
- traveller/modules/schedule/view.py
- traveller/static/themes/front/conftheme/2021/parts/final_talk_action.html
- traveller/static/themes/front/conftheme/2021/parts/schedule.html
- traveller/static/themes/front/conftheme/2021/parts/talk_actions.html
Reverts FlaskCon/traveller#156
> Revert "BugFix: When deleting talk in leaderboard (as admin) redirects to profile page."

- traveller/modules/cfp/forms.py
- traveller/modules/cfp/view.py
- traveller/static/themes/front/conftheme/2021/parts/cfp.html
- traveller/static/themes/front/conftheme/2021/parts/talk_actions.html
> BugFix: Author should not be able to tick out himself when editing his talk.

- traveller/static/themes/front/conftheme/2021/index.html
> Hide 100% flask and community driven cards on mobile.

- traveller/modules/cfp/view.py
- traveller/modules/schedule/forms.py
- traveller/modules/schedule/models.py
- traveller/modules/schedule/view.py
> BugFix: Add at talk form breaks when omitting end date (beginner).

- traveller/static/themes/front/conftheme/2021/index.html
Nothing much to see here - mainly just made the date look a little
better. Also added some padding to the bottom of staff bios so that
section is a less cramped.
> Tweak words, update styles

- .github/workflows/dev.yaml
testing github action triggers
> testing stg deploy

- traveller/static/themes/front/conftheme/2021/parts/final_talk_action.html
> fix: email on final talk action

- traveller/modules/schedule/models.py
- traveller/modules/schedule/view.py
This fixes issue #204 by ensuring the Day.date only accepts unique values
> BugFix: Scheduling or adding the same day for a conference more than once.

- traveller/static/themes/front/conftheme/2021/parts/review.html
> fix: notes to reviewing

- traveller/static/themes/front/conftheme/2021/index.html
> Fix message when cfp has ended

- traveller/modules/cfp/forms.py
- traveller/modules/cfp/view.py
- traveller/modules/conf/models.py
- traveller/modules/schedule/forms.py
- traveller/modules/schedule/models.py
- traveller/modules/y/tests/test_y_functional.py
- traveller/seed.py
- traveller/static/themes/front/conftheme/2021/parts/cfp.html
I have removed the duration from the submit talk form so we can use the start and end time for an activity as the duration.
> Fix duration issue.
